name: Build iKoolProxy for aarch64_cortex-a53

on:
  workflow_dispatch:   # 手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Initialize build environment
      run: |
        sudo apt update
        sudo apt install -y build-essential git wget curl unzip python3 rsync gawk \
            libncurses5-dev libncursesw5-dev zlib1g-dev libssl-dev libelf-dev \
            subversion flex bison g++ gperf

    - name: Get OpenWrt source
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git checkout openwrt-23.05

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Add iKoolProxy package
      run: |
        cd openwrt/package
        git clone https://github.com/iwrt/luci-app-ikoolproxy.git

    - name: Configure build
      run: |
        cd openwrt
        # 设置目标架构为 aarch64_cortex-a53
        echo "CONFIG_TARGET_armvirt=y" >> .config
        echo "CONFIG_TARGET_armvirt_64=y" >> .config
        echo "CONFIG_TARGET_armvirt_64_Default=y" >> .config
        echo "CONFIG_TARGET_ARCH_PACKAGES=aarch64_cortex-a53" >> .config
        echo "CONFIG_PACKAGE_luci-app-ikoolproxy=m" >> .config
        make defconfig

    - name: Build package
      run: |
        cd openwrt
        make package/luci-app-ikoolproxy/compile V=s -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ikoolproxy-ipk-aarch64_cortex-a53
        path: |
          openwrt/bin/packages/*/base/luci-app-ikoolproxy*.ipk
          openwrt/bin/packages/*/*/luci-app-ikoolproxy*.ipk
