name: Build ilxp luci-app-ikoolproxy (aarch64_cortex-a53)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt update
          sudo apt install -y build-essential git wget curl unzip python3 rsync gawk \
              libncurses5-dev libncursesw5-dev zlib1g-dev libssl-dev libelf-dev \
              subversion flex bison g++ gperf

      - name: Download OpenWrt SDK (use x86_64 generic)
        run: |
          mkdir sdk && cd sdk
          wget https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xJf openwrt-sdk-*.tar.xz --strip-components=1

      - name: Update and install feeds
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Add ilxp iKoolProxy package
        run: |
          cd sdk/package
          git clone https://github.com/ilxp/luci-app-ikoolproxy.git

      - name: Configure SDK
        run: |
          cd sdk
          echo "CONFIG_PACKAGE_luci-app-ikoolproxy=m" >> .config
          make defconfig

      - name: Build iKoolProxy
        run: |
          cd sdk
          make package/luci-app-ikoolproxy/compile V=s -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-ikoolproxy-ipk
          path: |
            sdk/bin/packages/*/*/luci-app-ikoolproxy*.ipk

      - name: Get build date
        id: buildtime
        run: echo "date=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          tag_name: ikoolproxy-aarch64
          name: "ilxp luci-app-ikoolproxy (aarch64_cortex-a53)"
          body: |
            📦 luci-app-ikoolproxy build

            🕒 Build time: ${{ steps.buildtime.outputs.date }}
            🔢 Run number: ${{ github.run_number }}
            🔗 Commit: ${{ github.sha }}
          draft: false
          prerelease: false
          files: |
            sdk/bin/packages/*/*/luci-app-ikoolproxy*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
