name: Build iKoolProxy for aarch64_cortex-a53

on:
  workflow_dispatch:   # 手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4   # 同时更新 checkout 版本

    - name: Initialize build environment
      run: |
        sudo apt update
        sudo apt install -y build-essential git wget curl unzip python3 rsync gawk \
            libncurses5-dev libncursesw5-dev zlib1g-dev libssl-dev libelf-dev \
            subversion flex bison g++ gperf

    - name: Get OpenWrt source
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git checkout openwrt-23.05

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Add iKoolProxy package
      run: |
